project:
  type: book

  pre-render:
    - R/generate-book-structure.R

  resources:
    - LICENSES/*.txt

profile:
  group:
    - [html, pdf]

metadata-files:
   - _book-structure.yml

lang: es

book:
  title: "Quarto Extensions Framework"
  subtitle: "Arquitectura, artefactos y metodología emergente"
  author: "Javier G. Grandez"

  chapters:
    - "index.qmd"

  navbar:
    left:
      - text: "Inicio"
        href: index.qmd

    right:
      - icon: github
        href: https://github.com/Grandez/iasi-lua
        aria-label: GitHub
    
  page-footer:
    left: "© 2026 Javier G. Grandez"
    right:
      - text: "Licencias"
        href: licenses.qmd

format:

  html:
    theme: cosmo
    toc: true
    toc-depth: 3
    number-sections: true
    code-copy: true
    code-overflow: wrap

  pdf:
    toc: true
    number-sections: true

filters:
  - extensions/plantuml/plantuml.lua

filter-options:

  plantuml:
    enabled: true
    server: http://javier:1025
    format: png
    cache: true
    styles:
      - resources/plantuml/iasi.puml

execute:
  freeze: auto

crossref:
  fig-title: Figura
  tbl-title: Tabla
  lst-title: Listado
  