#!/usr/bin/env bash

# Shared helpers for IASI Lua project automation.
# Intended for Bash on Linux and Bash environments on Windows (for example WSL).

set -euo pipefail

IASI_SCRIPTS_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
IASI_ROOT="$(cd "$IASI_SCRIPTS_DIR/.." && pwd)"

fail() {
  printf 'ERROR: %s\n' "$*" >&2
  exit 1
}

require_command() {
  command -v "$1" >/dev/null 2>&1 || fail "No se encuentra el comando requerido: $1"
}

extension_sources() {
  local manifest

  for manifest in "$IASI_ROOT"/*/_extension.yml; do
    [[ -f "$manifest" ]] || continue
    dirname "$manifest"
  done
}

extension_name() {
  basename "$1"
}

extension_id() {
  local source="$1"
  local manifest="$source/_extension.yml"
  local value

  value="$({
    awk '
      /^[[:space:]]*filters:[[:space:]]*$/ { in_filters = 1; next }
      in_filters && /^[[:space:]]*-[[:space:]]*[^#]+\.lua[[:space:]]*$/ {
        line = $0
        sub(/^[[:space:]]*-[[:space:]]*/, "", line)
        sub(/[[:space:]]*$/, "", line)
        gsub(/["\047]/, "", line)
        sub(/\.lua$/, "", line)
        print line
        exit
      }
      in_filters && /^[^[:space:]]/ { in_filters = 0 }
    ' "$manifest"
  } || true)"

  [[ -n "$value" ]] || fail "No se pudo determinar el id de la extensión desde $manifest"
  printf '%s\n' "$value"
}

extension_version() {
  local source="$1"
  local manifest="$source/_extension.yml"
  local value

  value="$({
    awk '
      /^version:[[:space:]]*/ {
        line = $0
        sub(/^version:[[:space:]]*/, "", line)
        sub(/[[:space:]]*#.*/, "", line)
        gsub(/^["\047]|["\047]$/, "", line)
        print line
        exit
      }
    ' "$manifest"
  } || true)"

  [[ -n "$value" ]] || fail "Falta version en $manifest"
  printf '%s\n' "$value"
}

extension_source() {
  local name="$1"
  local source="$IASI_ROOT/$name"

  [[ -d "$source" ]] || fail "Extensión desconocida: $name"
  [[ -f "$source/_extension.yml" ]] || fail "Falta $source/_extension.yml"

  printf '%s\n' "$source"
}

copy_extension_sources() {
  local source="$1"
  local target="$2"
  local entry
  local base

  while IFS= read -r -d '' entry; do
    base="$(basename "$entry")"

    case "$base" in
      tests|example.qmd)
        continue
        ;;
    esac

    cp -a "$entry" "$target/"
  done < <(find "$source" -mindepth 1 -maxdepth 1 -print0)
}

build_extension() {
  local source="$1"
  local target="$2"
  local version

  [[ -d "$IASI_ROOT/core" ]] || fail "Falta el core compartido: $IASI_ROOT/core"

  rm -rf "$target"
  mkdir -p "$target/core"

  cp -a "$IASI_ROOT/core/." "$target/core/"
  copy_extension_sources "$source" "$target"
  cp "$IASI_ROOT/LICENSE" "$target/LICENSE"

  version="$(extension_version "$source")"
  printf 'return "%s"\n' "$version" > "$target/version.lua"
  printf 'Generated by scripts/build-extension.sh. Do not edit here.\n' > "$target/.generated"
}

