skinparam Shadowing false
skinparam RoundCorner 8
skinparam DefaultFontName "Segoe UI"
skinparam DefaultFontSize 12
skinparam ArrowThickness 2
skinparam BackgroundColor white
skinparam linetype ortho
skinparam rectangle { BackgroundColor white BorderColor #2F5597 }
skinparam component { BackgroundColor white BorderColor #2F5597 }
skinparam database { BackgroundColor white BorderColor #70AD47 }
