from __future__ import annotations

import argparse
import re
import shutil
from pathlib import Path

from extensions import EXTENSIONS

ROOT = Path(__file__).resolve().parents[1]


def read_version(extension_file: Path) -> str:
    text = extension_file.read_text(encoding="utf-8")
    match = re.search(
        r"^version:\s*['\"]?([^'\"\s]+)",
        text,
        re.MULTILINE,
    )
    if match is None:
        raise RuntimeError(f"Falta version en {extension_file}")
    return match.group(1)


def copy_file(source: Path, target: Path) -> None:
    target.parent.mkdir(parents=True, exist_ok=True)
    shutil.copy2(source, target)


def copy_tree(source: Path, target: Path) -> None:
    shutil.copytree(source, target, dirs_exist_ok=True)


def build(name: str, destination: Path | None = None) -> Path:
    try:
        specification = EXTENSIONS[name]
    except KeyError as exc:
        available = ", ".join(sorted(EXTENSIONS))
        raise RuntimeError(
            f"Extension desconocida: {name}. Disponibles: {available}"
        ) from exc

    source = ROOT / specification["source"]
    target = destination or ROOT / specification["distribution"]

    if target.exists():
        shutil.rmtree(target)
    target.mkdir(parents=True)

    # Core is shared source, but every Quarto extension must be autonomous.
    copy_tree(ROOT / "core", target / "core")

    for relative in specification["files"]:
        copy_file(source / relative, target / relative)

    copy_file(ROOT / "LICENSE", target / "LICENSE")

    version = read_version(source / "_extension.yml")
    (target / "version.lua").write_text(
        f'return "{version}"\n',
        encoding="utf-8",
        newline="\n",
    )
    (target / ".generated").write_text(
        "Generated by scripts/build_extension.py. Do not edit here.\n",
        encoding="utf-8",
        newline="\n",
    )

    return target


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("extension", choices=sorted(EXTENSIONS))
    args = parser.parse_args()
    target = build(args.extension)
    print(f"Generada {target.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
